### ISSUE TITLE
C4D Importer

### ISSUE THREAD

**Issue by mastajappa** [Marlamin/WoWExportTools#15]
Hi I've tried the Exporter. And this creates a nice folder with all the assets but when I want to use it with the importer it doesn't recognize all the obj files in the directory. For instance I've tried to export Dalaran but when using the import plugin only a chest and an axe seem to be selectable. The rest of the files which are there are not showing.

**Comment by Marlamin** [comment]
Sadly haven't heard from the C4D plugin author in a while, so closing this.
