### ISSUE TITLE
Blender Import Tools Bugs

### ISSUE THREAD

**Issue by reddohme** [Marlamin/WoWExportTools#20]
Like my previous issue report, these issues were known but did not have a dedicated post.
**WMOs and M2s do not import with proper positioning**
When importing an adt to Blender (and by extension exporting it) the objects (wmos and m2s) won't be in their proper position, and will be offset (using unity to show the example since Blender crashes when I have everything loaded with textures because my avaliable.) Highmountain (adt trollraid22_23)
![image](https://user-images.githubusercontent.com/37015524/38639136-3246ab2a-3d85-11e8-9d38-e18f670dac8e.png)
![image](https://user-images.githubusercontent.com/37015524/38639147-37a9aa7c-3d85-11e8-8e4c-26b75ff46e13.png)

You can see objects floating, the lodge and other objects do not actually align to the road. A better example on picture 2 shows where the mini arena should be versus where it actually gets imported.

Here is a picture of how it should work (not 100% accurate but much closer than the initial import)
![image](https://user-images.githubusercontent.com/37015524/38639294-94c5d398-3d85-11e8-9fba-40678d7db2b7.png)

**Importing multiple adts with one session in blender, will only import the objects for one adt.**
Example: if you import adt1, all objects will be present. If you then import adt2, the objects from adt won't be present.
This may be something on my end, end user solution is to simply import one adt per file, export, then start a new instance and export. Leaving about one exported file per adts. Realistically, I'm unsure if this is even an issue, it might lead to cleaner project files, being able to individually edit adt objects rather than an entire map space for a minor change.

Cheers

**Comment by Marlamin** [comment]
For floating stuff, moving the "WMOs" and "Doodads" groups to 0,0,0 should fix it for now. Looking into the importing multiple ADTs issue.

**Comment by Marlamin** [comment]
The multiple ADT issue should be fixed in the new plugin which will eventually replace the two old ones.
