### ISSUE TITLE
ADT Import takes a very long time

### ISSUE THREAD

**Issue by Tenshinen** [Marlamin/WoWExportTools#21]
Blender sits using a full core, the commit and RAM usage very very slowly increase (we're talking a few KB every couple seconds) and the disk usage is literally 0. If I wait long enough, it eventually works fine. Why does it take so long, though? Is it not possible to speed it up somehow? D;

**Comment by Tenshinen** [comment]
I agree it'd be nice to skip Blender entirely if possible. :o

Another thing I have noticed: Importing the ADT as a raw OBJ is perfectly
fine speeds, which makes it feel like the issue is with the importing of
the included WMOs? :o

P.S. This is just question but: why does the 16k option split the files?
Can PNG not support 16k res?

**Comment by Marlamin** [comment]
So the newest release has a new plugin that should import ADTs significantly faster. If you're still experiencing these issues I suggest you try that.
