### ISSUE TITLE
"Open File Browser" button in the C4D importer not working?

### ISSUE THREAD

**Issue by mheramb** [Marlamin/WoWExportTools#28]
Clicking "Open File Browser" button in the C4D importer plugin does nothing. I have to copy/paste the file location into the field, because the button does not open the file browser.
![Open File Browser](https://user-images.githubusercontent.com/48392263/54076350-1aeb9b80-42ab-11e9-90d4-0deccfe30b29.png)

**Comment by Marlamin** [comment]
Haven't heard of the C4D plugin author in a while so closing this, sorry.
