### ISSUE TITLE
Do not import the model into blender 8nzj_nazjatar_palace01_2355242.obj

### ISSUE THREAD

**Issue by Jarek250** [Marlamin/WoWExportTools#40]
world / wmo / nazjatar / 8nzj_nazjatar_palace01_2355242.wmo
such messages appear
![Bez tytułu](https://user-images.githubusercontent.com/23528174/60845628-388b2c00-a1dd-11e9-9084-e604be1555f4.png)

**Comment by Marlamin** [comment]
Thanks for the report, will look into this soon.

**Comment by Marlamin** [comment]
It turns out this is a Blender limitation with the maximum number of textures per mesh being 18. Not something I can easily fix on my end, sorry.
