### ISSUE TITLE
Blender import error when importing Zandalar_29_33

### ISSUE THREAD

**Issue by Marlamin** [Marlamin/WoWExportTools#43]
![image](https://user-images.githubusercontent.com/50212/62863782-1cae0500-bd0a-11e9-9f16-cec649ad86e6.png)

**Comment by Kruithne** [comment]
As per our discussion on Discord, adding to this issue:

There are inconsistencies with the exporter when it comes to maps with spaces in them. A map such as 'troll raid' exports as such:

- Directory named 'troll raid', should be 'trollraid'.
- OBJ/MTL/Textures prefixed 'trollraid', this is fine.
- MTL defines textures prefixed 'trollraid', this is fine.
- OBJ references MTL prefixes as 'troll raid', this breaks importing.

**Comment by Marlamin** [comment]
Fixed in 2b84341, thanks!

> As per our discussion on Discord, adding to this issue:
> 
> There are inconsistencies with the exporter when it comes to maps with spaces in them. A map such as 'troll raid' exports as such:
> 
> * Directory named 'troll raid', should be 'trollraid'.
> * OBJ/MTL/Textures prefixed 'trollraid', this is fine.
> * MTL defines textures prefixed 'trollraid', this is fine.
> * OBJ references MTL prefixes as 'troll raid', this breaks importing.

Fixed in d85346d, thanks.
