### ISSUE TITLE
Bad quality of exported trees

### ISSUE THREAD

**Issue by Fixjunior** [Marlamin/WoWExportTools#77]
When i export location to Cinema 4D,  textures of all objects are normal, except tree textures. 
At the edges of the leaves you can see green pieces of texture that should be transparent. Tell me please, how to fix it? 
![tree](https://user-images.githubusercontent.com/64223869/80138682-d81f7c80-85ad-11ea-91c3-689aa05a5aed.png)

**Comment by Marlamin** [comment]
Hey, you'll have to figure out how to deal with the alpha values of that texture yourself, that's not something the software will or can do for you. Also, the software in this repo is no longer supported and has been replaced by https://wow.tools/export/.

**Comment by Fixjunior** [comment]
> Hey, you'll have to figure out how to deal with the alpha values of that texture yourself, that's not something the software will or can do for you. Also, the software in this repo is no longer supported and has been replaced by https://wow.tools/export/.

The latest version of this program doesn't work, that's why i use previous version.  It's just infinitely installing. Also, both this and other previous versions can't export files to OBJ format, it export them in MTL format, and Cinema 4D just don't see this file. To solve this problem, I first imported these files to Blender, and from Blender to Cinema 4D. Why does this texture requires my intervention, I saw a lot of videos on YouTube where people export locations, and they didn’t have such a bug with tree textures? Thank you for answering, by the way.

**Comment by Marlamin** [comment]
If you can expand on what "infinitely installing" means that'd be neat so we can look at that issue. The MTL files are part of the OBJ format and are what describes the textures of OBJ files. Both exporters export those. I'm not sure why the tree is acting differently, but many things will need manual fixing as WoW and regular 3D file formats are very different.

**Comment by Fixjunior** [comment]
Infinitely installing means that the installation of this program each time stops at the same moment. Do you think, that texture may be displayed differently due to program versions?
![ыыы](https://user-images.githubusercontent.com/64223869/80156922-be8e2d00-85cd-11ea-82ae-4bb1fa2db829.PNG)

**Comment by Marlamin** [comment]
That step can take a while, but I'm a bit busy at the moment so can't help further for now. Maybe you can join the Discord for wow.export (https://discord.gg/52mHpxC) and ask for support there. Maybe someone can help you.
