### ISSUE TITLE
[Question] Adding In game GameObjects to meshes

### ISSUE THREAD

**Issue by Rokeo** [Marlamin/WoWExportTools#78]
Hi there!

Can you tell is there a way to get model file id (which used in CASC) for in-game object, which not exist in the mesh itself?
For example, such objects are mailboxes - those not baked in mesh as far as I know but exist in-game.
In the human starting zone where the player is spawned, there is also one, it has in-game id:
<Object "Mailbox" Entry="202578" X="-8907.201" Y="-130.0747" Z="80.798" />

Thanks in advance!

**Comment by Marlamin** [comment]
Sorry for not responding to this earlier, this repository is no longer actively maintained. 

To answer your question, I don't really know, I think you might be able to link those IDs up via gameobjectcache, but not sure.
